trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  webRepository: 'tailspin-web'
  tag: '$(Build.BuildId)'
  containerRegistry: 'tailspinspacegame26514.azurecr.io'
  azureSubscription: 'Resource Manager - Tailspin - Space Game'

stages:
- stage: 'Build'
  displayName: 'Construcción de la aplicación web'
  jobs: 
  - job: 'Build'
    displayName: 'Tarea de construcción'
    pool:
      name: RetoAzure
      demands:
      - agent.name -equals MyAgent

    steps:
    - task: Docker@2
      displayName: 'Construir y enviar la imagen a ACR'
      inputs:
        command: buildAndPush
        repository: $(webRepository)
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        containerRegistry: 'tailspinspacegame26514.azurecr.io'
        tags: |
          $(tag)

- stage: 'Deploy'
  displayName: 'Desplegar el contenedor'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Tarea de despliegue'
    pool:
      name: RetoAzure
      demands:
      - agent.name -equals MyAgent

    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Desplegar en Azure App Service'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: '$(WebAppName)'
        containers: '$(containerRegistry)/$(webRepository):$(tag)'