trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  webRepository: 'tailspin-web'  # Nombre de la imagen en ACR
  tag: '$(Build.BuildId)'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '8.x'
  containerRegistry: 'Resource Manager - Tailspin - Space Game'  # Nombre de la conexión de ACR en Azure DevOps
  azureSubscription: 'Resource Manager - Tailspin - Space Game'  # Conexión a Azure RM

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      name: RetoAzure
      demands:
      - agent.name -equals MyAgent

    steps:
    - task: Docker@2
      displayName: 'Build and push the image to ACR'
      inputs:
        command: buildAndPush
        repository: $(RegistryName)/$(webRepository)  # Usamos la variable de Library
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        containerRegistry: $(containerRegistry)
        tags: |
          $(tag)

- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      name: RetoAzure
      demands:
      - agent.name -equals MyAgent
    variables:
    - group: Release  # 🔹 Importa la Library "Release"
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy to Azure App Service'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(WebAppName)  # Usamos la variable de Library
        containers: '$(RegistryName)/$(webRepository):$(Build.BuildId)'
